# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EnableViewDebuggingExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ZYUIDebuggingInformationOverlay'
  # Pods for EnableViewDebuggingExample

end
